// AUTO-GENERATED by scripts/build-splash.mjs — do not edit by hand.
// Feeds metadata.appleWebApp.startupImage in app/layout.js. iOS picks the
// matching image by prefers-color-scheme (OS theme) + device dimensions.
export const appleStartupImages = [
  {
    "url": "/splash/iphone-se-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-xr-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-x-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-xs-max-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-12-mini-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-12-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-14-plus-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-14-pro-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-15-pro-max-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-16-pro-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-16-pro-max-light.png",
    "media": "(prefers-color-scheme: light) and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-se-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-xr-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-x-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-xs-max-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-12-mini-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-12-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-14-plus-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-14-pro-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-15-pro-max-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-16-pro-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "url": "/splash/iphone-16-pro-max-dark.png",
    "media": "(prefers-color-scheme: dark) and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  }
];
