import sharp from "sharp";
import { readFile, writeFile, mkdir } from "node:fs/promises";

// iOS launch (splash) screens. iOS renders these BEFORE the app JS runs, so it
// can only key off prefers-color-scheme (the OS theme), never the in-app manual
// toggle. Wordmark centered on a solid bg, tinted per theme.

const wordmark = await readFile("public/brand/wordmark.svg", "utf8");
const tint = (svg, color) => svg.replaceAll("currentColor", color);

const THEMES = {
  light: { bg: "#FEFEFF", fg: "#0F0F0F" },
  dark: { bg: "#0F0F0F", fg: "#FEFEFF" },
};

// device-width/height are CSS logical px (for the media query) ; w/h are the
// physical pixels of the generated PNG (= css × dpr).
const DEVICES = [
  { name: "iphone-se", cssW: 375, cssH: 667, dpr: 2 },
  { name: "iphone-xr", cssW: 414, cssH: 896, dpr: 2 },
  { name: "iphone-x", cssW: 375, cssH: 812, dpr: 3 },
  { name: "iphone-xs-max", cssW: 414, cssH: 896, dpr: 3 },
  { name: "iphone-12-mini", cssW: 360, cssH: 780, dpr: 3 },
  { name: "iphone-12", cssW: 390, cssH: 844, dpr: 3 },
  { name: "iphone-14-plus", cssW: 428, cssH: 926, dpr: 3 },
  { name: "iphone-14-pro", cssW: 393, cssH: 852, dpr: 3 },
  { name: "iphone-15-pro-max", cssW: 430, cssH: 932, dpr: 3 },
  { name: "iphone-16-pro", cssW: 402, cssH: 874, dpr: 3 },
  { name: "iphone-16-pro-max", cssW: 440, cssH: 956, dpr: 3 },
];

await mkdir("public/splash", { recursive: true });

const entries = [];

for (const theme of Object.keys(THEMES)) {
  const { bg, fg } = THEMES[theme];
  const wm = Buffer.from(tint(wordmark, fg));
  for (const d of DEVICES) {
    const w = d.cssW * d.dpr;
    const h = d.cssH * d.dpr;
    const wmPng = await sharp(wm, { density: 512 })
      .resize({ width: Math.round(w * 0.42) })
      .png()
      .toBuffer();
    const out = `public/splash/${d.name}-${theme}.png`;
    await sharp({ create: { width: w, height: h, channels: 4, background: bg } })
      .composite([{ input: wmPng, gravity: "center" }])
      .png({ compressionLevel: 9, palette: true })
      .toFile(out);
    console.log(`✓ ${out} (${w}×${h})`);

    entries.push({
      url: `/splash/${d.name}-${theme}.png`,
      media: `(prefers-color-scheme: ${theme}) and (device-width: ${d.cssW}px) and (device-height: ${d.cssH}px) and (-webkit-device-pixel-ratio: ${d.dpr}) and (orientation: portrait)`,
    });
  }
}

const module = `// AUTO-GENERATED by scripts/build-splash.mjs — do not edit by hand.
// Feeds metadata.appleWebApp.startupImage in app/layout.js. iOS picks the
// matching image by prefers-color-scheme (OS theme) + device dimensions.
export const appleStartupImages = ${JSON.stringify(entries, null, 2)};
`;

await writeFile("lib/splashScreens.js", module);
console.log(`✓ lib/splashScreens.js (${entries.length} entries)`);
